/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/usuarios/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["buscar"];
        put?: never;
        post: operations["cadastrar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CadastroRequest: {
            nome: string;
            /** @enum {string} */
            perfil: "ESTUDANTE" | "PROFISSIONAL";
            instituicao?: string;
            /** Format: int32 */
            periodo?: number;
            /** @enum {string} */
            categoria?: "FISIOTERAPEUTA" | "TERAPEUTA_OCUPACIONAL" | "OUTRA";
            registro?: string;
            /** @enum {string} */
            uf?: "AC" | "AL" | "AP" | "AM" | "BA" | "CE" | "DF" | "ES" | "GO" | "MA" | "MT" | "MS" | "MG" | "PA" | "PB" | "PR" | "PE" | "PI" | "RJ" | "RN" | "RS" | "RO" | "RR" | "SC" | "SP" | "SE" | "TO";
            aceiteTermos: boolean;
        };
        AtualizarPerfilProfissionalRequest: {
            /** @enum {string} */
            categoria: "FISIOTERAPEUTA" | "TERAPEUTA_OCUPACIONAL" | "OUTRA";
            registro: string;
            /** @enum {string} */
            uf: "AC" | "AL" | "AP" | "AM" | "BA" | "CE" | "DF" | "ES" | "GO" | "MA" | "MT" | "MS" | "MG" | "PA" | "PB" | "PR" | "PE" | "PI" | "RJ" | "RN" | "RS" | "RO" | "RR" | "SC" | "SP" | "SE" | "TO";
        };
        UsuarioResponse: {
            /** Format: uuid */
            id: string;
            nome: string;
            /** @enum {string} */
            perfil: "ESTUDANTE" | "PROFISSIONAL";
            revisor: boolean;
            instituicao?: string;
            /** Format: int32 */
            periodo?: number;
            /** @enum {string} */
            categoria?: "FISIOTERAPEUTA" | "TERAPEUTA_OCUPACIONAL" | "OUTRA";
            registro?: string;
            /** @enum {string} */
            uf?: "AC" | "AL" | "AP" | "AM" | "BA" | "CE" | "DF" | "ES" | "GO" | "MA" | "MT" | "MS" | "MG" | "PA" | "PB" | "PR" | "PE" | "PI" | "RJ" | "RN" | "RS" | "RO" | "RR" | "SC" | "SP" | "SE" | "TO";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    buscar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UsuarioResponse"];
                };
            };
        };
    };
    cadastrar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CadastroRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["UsuarioResponse"];
                };
            };
        };
    };
}
