-- Dicionário de parâmetros do aparelho (guia técnico, seção 12), nos três grupos do card.
-- A ordem dos inserts é a ordem da tela: a API ordena pelo id.

create table parametro_dicionario (
    id               bigint       generated by default as identity primary key,
    nome             varchar(60)  not null unique,
    grupo            varchar(30)  not null check (grupo in ('AJUSTE_BASICO', 'RECURSO_ESPECIFICO', 'ESPECIFICACAO_ELETRICA')),
    unidade          varchar(10),
    unidade_extenso  varchar(30),
    o_que_muda       text         not null,
    exemplo          text         not null,
    -- O leitor de tela precisa da unidade por extenso ("µs" -> "microssegundos").
    constraint parametro_unidade_com_extenso check (unidade is null or unidade_extenso is not null)
);

alter table parametro_dicionario enable row level security;

insert into parametro_dicionario (nome, grupo, unidade, unidade_extenso, o_que_muda, exemplo) values
('Frequência', 'AJUSTE_BASICO', 'Hz', 'hertz',
    'Número de pulsos por segundo. No modo burst pode existir outra frequência, a das rajadas.',
    '80 Hz = 80 pulsos por segundo.'),
('Largura de pulso', 'AJUSTE_BASICO', 'µs', 'microssegundos',
    'Tempo de uma fase ou de um pulso, conforme a definição do manual do aparelho. Fase não é necessariamente o pulso completo.',
    '300 µs = 0,3 ms. Confundir 300 µs com 300 ms aumenta a duração em 1.000 vezes.'),
('Intensidade', 'AJUSTE_BASICO', 'mA', 'miliampères',
    'Valor de corrente mostrado pelo aparelho. Está ligado ao recrutamento e à sensação. Não existe um valor que sirva para todos.',
    'Carga por fase: Q = I × t. 20 mA × 200 µs = 4 µC. Esse cálculo sozinho não define segurança nem dose.'),
('Duração da sessão', 'AJUSTE_BASICO', 'min', 'minutos',
    'Tempo total programado da sessão. Não confundir com a duração de um pulso ou de uma contração.',
    '20 min no exercício didático de TENS convencional.'),
('Forma de onda', 'RECURSO_ESPECIFICO', null, null,
    'Desenho da corrente ao longo do tempo: monofásica, bifásica etc. A aparência da onda sozinha não indica eficácia.',
    'Um pulso bifásico tem duas fases.'),
('Rampa de subida', 'RECURSO_ESPECIFICO', 's', 'segundos',
    'Tempo de aumento gradual até a intensidade do ciclo. Deixa o início da contração mais confortável.',
    'Subida de 2 s no Exercício A (ativação de quadríceps).'),
('Rampa de descida', 'RECURSO_ESPECIFICO', 's', 'segundos',
    'Tempo de redução gradual da intensidade no fim do ciclo.',
    'Descida de 2 s no Exercício A (ativação de quadríceps).'),
('Estímulo (tempo ON)', 'RECURSO_ESPECIFICO', 's', 'segundos',
    'Período com estimulação. Aqui inclui subida, platô e descida. Alguns fabricantes chamam de ON só o platô.',
    'Subida 2 s + platô 6 s + descida 2 s = ON de 10 s.'),
('Repouso (tempo OFF)', 'RECURSO_ESPECIFICO', 's', 'segundos',
    'Período sem estimulação entre um ciclo e outro.',
    'ON de 10 s e OFF de 30 s: ciclo de 40 s, ciclo de trabalho de 25% (relação 1:3).'),
('Alimentação', 'ESPECIFICACAO_ELETRICA', 'V', 'volts',
    'Energia que chega ao aparelho pela rede, fonte ou bateria. Não é um parâmetro da sessão.',
    'Os 127 V ou 220 V da tomada não dizem nada sobre a dose aplicada.'),
('Tensão de saída', 'ESPECIFICACAO_ELETRICA', 'V', 'volts',
    'Diferença de potencial produzida na saída do aparelho, nas condições informadas pelo fabricante. É diferente da intensidade em mA.',
    'O valor vem da especificação técnica do manual do modelo.');
